---
- name: Create GKE Cluster
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Create a GKE cluster
      google.cloud.gcp_container_cluster:
        name: gke-cluster01
        initial_node_count: 2
        node_config:
          machine_type: n1-standard-4
          disk_size_gb: 500
        location: us-east1-b
        project: ansiblegcp-375015
        auth_kind: serviceaccount
        state: present
      register: cluster

    - name: Create a node pool for the GKE cluster
      google.cloud.gcp_container_node_pool:
        name: gke-nodepool01
        initial_node_count: 2
        cluster: "{{ cluster }}"
        location: us-east1-b
        project: ansiblegcp-375015
        auth_kind: serviceaccount
        state: present
