---
- name: Create GCP Project
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Create a Google Cloud Project
      google.cloud.gcp_resourcemanager_project:
        name: "{{ parent_name }}"
        id: "{{ parent_resource_id }}"
        type: "{{ parent_resource_type }}"
        auth_kind: serviceaccount
        state: present
