---
- name: Create GCP resources and then create a GCP instance
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Create a disk mapped from a RHEL-9 image
      google.cloud.gcp_compute_disk:
        name: "{{ item.name }}"
        size_gb: 50
        source_image: "projects/rhel-cloud/global/images/rhel-9-v20221102"
        zone: "{{ gcp_zone }}"
        project: "{{ gcp_project }}"
        auth_kind: serviceaccount
        state: present
      with_items:
        - {name: 'rhel1d'}
        - {name: 'rhel2d'}
      register: disk

    - name: Create a Google Virtual Private Cloud (VPC) network
      google.cloud.gcp_compute_network:
        name: network-instance
        auto_create_subnetworks: 'true'
        project: "{{ gcp_project }}"
        auth_kind: serviceaccount
        state: present
      register: network

    - name: Create a firewall rule to allow SSH
      google.cloud.gcp_compute_firewall:
        name: allowssh
        allowed:
          - ip_protocol: tcp
            ports:
              - '22'
              - '80'
              - '443'
        target_tags:
          - sshallowed
        project: "{{ gcp_project }}"
        network: "{{ network }}"
        auth_kind: serviceaccount
        state: present
      register: sshallowed

    - name: Create an IPv4 public IP address
      google.cloud.gcp_compute_address:
        name: "{{ item.name }}"
        region: "{{ gcp_region }}"
        project: "{{ gcp_project }}"
        auth_kind: serviceaccount
        state: present
      with_items:
        - {name: 'rhel1ip'}
        - {name: 'rhel2ip'}
      register: ipaddress

    - name: Create the rhel1 VM instances
      google.cloud.gcp_compute_instance:
        name: rhel1
        machine_type: n1-standard-1
        disks:
          - auto_delete: 'true'
            boot: 'true'
            source:
              - "{{ disk[0] }}"
          - auto_delete: 'true'
            interface: NVME
            type: SCRATCH
            initialize_params:
              disk_type: local-ssd
        labels:
          environment: production
        network_interfaces:
          - network: "{{ network }}"
            access_configs:
              - name: External NAT
                nat_ip: rhel1ip
                type: ONE_TO_ONE_NAT
        zone: "{{ gcp_zone }}"
        project: "{{ gcp_project }}"
        auth_kind: serviceaccount
        state: present

    - name: Create the rhel2 VM instances
      google.cloud.gcp_compute_instance:
        name: rhel2
        machine_type: n1-standard-1
        disks:
          - auto_delete: 'true'
            boot: 'true'
            source:
              - rhel2d
          - auto_delete: 'true'
            interface: NVME
            type: SCRATCH
            initialize_params:
              disk_type: local-ssd
        labels:
          environment: production
        network_interfaces:
          - network: "{{ network }}"
            access_configs:
              - name: External NAT
                nat_ip: rhel2ip
                type: ONE_TO_ONE_NAT
        zone: "{{ gcp_zone }}"
        project: "{{ gcp_project }}"
        auth_kind: serviceaccount
        state: present
##