- name: Deploy Vertex AI ML Pipeline
  hosts: localhost
  gather_facts: false
  vars:
    gcp_project: "my-gcp-project"
    gcp_region: "us-east1"
    resource_name: "vertex-ai"
    
  tasks:
  - name: Create Vertex AI NETWORK
    google.cloud.gcp_compute_network:
      name: "{{ resource_name }}-network"
      state: present
      auto_create_subnetworks: true
      project: "{{ gcp_project }}"
    register: _network

  - name: Deploy Vertex AI endpoint with Model Garden deployment
    google.cloud.gcp_vertexai_endpoint_with_model_garden_deployment:
      state: present
      publisher_model_name: "publishers/google/models/paligemma@paligemma-224-float32"
      endpoint_config:
        endpoint_display_name: "{{ resource_name }}-endpoint"
      model_config:
        model_display_name: "{{ resource_name }}-model"
        accept_eula: true
      location: "{{ gcp_region }}"
      project: "{{ gcp_project }}"
    register: _mydeploy

  - name: Run assertions
    ansible.builtin.assert:
      that:
        - _mydeploy.changed == true


#   - name: Destroy Basic Model
#     google.cloud.gcp_vertexai_endpoint_with_model_garden_deployment:
#       state: absent
#       publisher_model_name: "publishers/google/models/paligemma@paligemma-224-float32"
#       endpoint_config:
#         endpoint_display_name: "{{ resource_name }}-endpoint"
#       model_config:
#         model_display_name: "{{ resource_name }}-model"
#         accept_eula: true
#       location: "{{ gcp_region }}"
#       project: "{{ gcp_project }}"

#   - name: Destroy test network
#     google.cloud.gcp_compute_network:
#       state: absent
#       name: "{{ resource_name }}-network"
#       project: "{{ gcp_project }}"
