---
- name: Destroy GCP VM instance and it's resources
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Destroy a VM instance
      google.cloud.gcp_compute_instance:
        name: "{{ item.name }}"
        labels:
          environment: production
        zone: "{{ gcp_zone }}"
        project: "{{ gcp_project }}"
        auth_kind: serviceaccount
        state: absent
      with_items:
        - {name: 'rhel1'}
        - {name: 'rhel2'}

    - name: Destroy an IPv4 public IP address
      google.cloud.gcp_compute_address:
        name: "{{ item.name }}"
        region: "{{ gcp_region }}"
        project: "{{ gcp_project }}"
        auth_kind: serviceaccount
        state: absent
      with_items:
        - {name: 'rhel1ip'}
        - {name: 'rhel2ip'}

    - name: Destroy a firewall rule
      google.cloud.gcp_compute_firewall:
        name: allowssh
        project: "{{ gcp_project }}"
        network: projects/ansiblegcp-375015/global/networks/network-instance
        auth_kind: serviceaccount
        state: absent          

    - name: Destroy a Google Virtual Private Cloud (VPC) network
      google.cloud.gcp_compute_network:
        name: "network-instance"
        auto_create_subnetworks: 'true'
        project: "{{ gcp_project }}"
        auth_kind: serviceaccount
        state: absent

    - name: Destroy a disk mapped from a vm image
      google.cloud.gcp_compute_disk:
        name: "{{ item.name }}"
        zone: "{{ gcp_zone }}"
        project: "{{ gcp_project }}"
        auth_kind: serviceaccount
        state: absent
      with_items:
        - {name: 'rhel1d'}
        - {name: 'rhel2d'}
#