---
- name: Grab some specific details about the GCP VM instances and display them
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    vm_region: "{{ gcp_region | default('us-east1') }}"
    filter_tag: "{{ your_tag | default('*')}}"

  tasks:

    - name: Retrieve info for the GCP VM instances
      google.cloud.gcp_compute_instance_info:
        project: "{{ gcp_project }}"
        zone: "{{ gcp_zone }}"
        auth_kind: serviceaccount
      register: gcp_instance_info

    - name: Display GCP VM information to terminal
      ansible.builtin.debug:
        msg: "{{ gcp_instance_info.resources }}"

    - name: Display GCP VM information to terminal
      ansible.builtin.debug:
        msg:
          - "VM Instance Name:             {{ item.name | default('The tag *Name* Does not exist') }}"
          - "VM Instance HostName:         {{ item.hostname | default('The tag *HostName* Does not exist') }}"
          - "VM VPC Network:               {{ item.networkInterfaces[subnetwork] }}"         
          - "VM Instance ID:               {{ item.id }}"
          - "VM Labels:                    {{ item.labels  | default('NO *Labels exist') }}"   
          - "VM Instance Private IP:       {{ item.networkInterfaces[networkIP] | default('The *Private IP Address* Does not exist') }}"
          - "VM Instance Public IP:        {{ item.networkInterfaces[accessConfigs][natIP] | default('The *Public IP Address* Does not exist') }}"
          - "VM Instance State:            {{ item.status }}"
      loop: "{{ gcp_instance_info.resources }}"
      loop_control:
        label: "Display the VM information that we desire"
