---
- hosts: "{{ HOSTS }}"
  become: yes
  become_user: root
  vars:
    report_server: reportsrvr1
  
  tasks:
  - ansible.builtin.include_role:
      name: "demo.patching.patch_linux"

  - block:

    - ansible.builtin.include_role:
        name: "{{ item }}"
      loop:
        - "demo.patching.report_server"
        - "demo.patching.report_linux"
        - "demo.patching.report_linux_patching"

    - ansible.builtin.include_role:
        name: "demo.patching.report_server"
        tasks_from: linux_landing_page
        
    delegate_to: "{{ report_server }}"
    run_once: yes
