---
- name: Shutdown a GCP vm instance by name
  hosts: localhost
  connection: local
  gather_facts: false
  # become: yes
  # become_user: root
  # vars:
  #   vmname: "{{ vm_name }}"
  tasks:
    # - name: Shuting down a GCP vm by name
    #   community.general.shutdown:
    #     delay: 2
  #
  # hosts: localhost
  # gather_facts: false
  # tasks:
    - name: Retrieve info for the GCP VM instances
      google.cloud.gcp_compute_instance_info:
        project: "{{ gcp_project }}"
        zone: "{{ gcp_zone }}"
        auth_kind: serviceaccount
      register: gcp_instance_info

    - name: Stop the desired GCP VM instance
      google.cloud.gcp_compute_instance:
        project: "{{ gcp_project }}"
        zone: "{{ gcp_zone }}"
        auth_kind: serviceaccount
        status: "TERMINATED"
        deletion_protection: false
#      loop: "{{ gcp_instance_info.resources }}"
      when: gcp_instance_info.resources[0].name == vm_name
