---
- name: Shutdown a GCP vm instance by name
  hosts: "{{ vm_name }}"
  gather_facts: false
  become: yes
  become_user: root

  tasks:
    - name: Shuting down a GCP RHEL vm by name
      community.general.shutdown:
        delay: 2
        msg: "Shut down initiated by Ansible"
