---
- name: Grab some specific details about the GCP VM instances and display them
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Retrieve info for the GCP VM instances
      google.cloud.gcp_compute_instance_info:
        project: "{{ gcp_project }}"
        zone: "{{ gcp_zone }}"
        auth_kind: serviceaccount
      register: gcp_instance_info

    - name: Stop the desired GCP VM instance
      google.cloud.gcp_compute_instance:
        name: "{{ vm_name }}"
        # machine_type: n1-standard-1
        machine_type: n1-standard-1
        disks:
        - auto_delete: 'false'
          initialize_params:
            disk_type: local-ssd
        project: "{{ gcp_project }}"
        zone: "{{ gcp_zone }}"
        auth_kind: serviceaccount
        state: present
        status: TERMINATED
        deletion_protection: true
      loop: "{{ gcp_instance_info.resources }}"
      when: item.name == "{{ vm_name }}"
