---
- name: Grab some specific details about the GCP VM instances and display them
  hosts: "{{ vm_name }}"
  gather_facts: false
  
  tasks:
    - name: Stop the desired GCP VM instance
      community.general.shutdown:
        delay: 3
