---
- name: Shutdown a GCP vm instance by name
  hosts: "{{ vm_name }}"
  gather_facts: false
  become: yes
  tasks:
    - name: Shuting down a GCP vm by name
      ansible.builtin.command: "shutdown -h now"
  #
  # hosts: localhost
  # gather_facts: false
  # tasks:
  #   - name: Retrieve info for the GCP VM instances
  #     google.cloud.gcp_compute_instance_info:
  #       project: "{{ gcp_project }}"
  #       zone: "{{ gcp_zone }}"
  #       auth_kind: serviceaccount
  #     register: gcp_instance_info

  #   - name: Stop the desired GCP VM instance
  #     google.cloud.gcp_compute_instance:
  #       name: "{{ vm_name }}"
  #       project: "{{ gcp_project }}"
  #       zone: "{{ gcp_zone }}"
  #       auth_kind: serviceaccount
  #       status: "TERMINATED"
  #       deletion_protection: true
  #     loop: "{{ gcp_instance_info.resources }}"
  #     when: item.name == "{{ vm_name }}"

