---
- name: Shutdown a GCP vm instance by name
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    # - name: Shuting down a GCP vm by name
    #   community.general.shutdown:
    #     delay: 2
  #
    - name: Retrieve info for the GCP VM instances
      google.cloud.gcp_compute_instance_info:
        project: "{{ gcp_project }}"
        zone: "{{ gcp_zone }}"
        auth_kind: serviceaccount
      register: gcp_instance_info

    - name: Power off the desired GCP VM instance
      google.cloud.gcp_compute_instance:
        name: "{{ gcp_instance_info.resources[0].name }}"
        machine_type: n1-standard-1
        disks:
          - auto_delete: true
            boot: true
            initialize_params:
              source_image: projects/ubuntu-os-cloud/global/images/family/ubuntu-minimal-2204-lts
        labels:
          environment: production
        network_interfaces:
          - network: "{{ network }}"
            access_configs:
              - name: External NAT
                nat_ip: "{{ address }}"
                type: ONE_TO_ONE_NAT
        zone: "{{ gcp_zone }}"
        project: "{{ gcp_project }}"
        auth_kind: serviceaccount
        service_account_file: "{{ _service_account_file_ }}"
        state: absent
    

    
