- name: retrieve vpc information
  amazon.aws.ec2_vpc_net_info:
    region: "{{ ec2_region }}"
  register: vpc_info
  delegate_to: localhost

- name: retrieve info for ec2 instances
  amazon.aws.ec2_instance_info:
    region: "{{ ec2_region }}"
  register: ec2_instance_info
  delegate_to: localhost

- name: Gather information about Internet Gateways IGWs
  amazon.aws.ec2_vpc_igw_info:
    region: "{{ ec2_region }}"
  register: igw_info
  delegate_to: localhost

# - name: grab boto version
#   command: "{{ ansible_python['executable'] }} -c 'import boto3; print(boto3.__version__)'"
#   register: py_cmd
#   delegate_to: localhost

- name: grab information about AWS user
  amazon.aws.aws_caller_info:
    region: "{{ ec2_region }}"
  register: whoami
  delegate_to: localhost

- name: print whoami
  debug:
    var: whoami
  delegate_to: localhost

- name: save username of AWS user
  set_fact:
    aws_user: '{{ whoami.arn.split("/")[-1] }}'
    py_cmd: >-
      {{ lookup('pipe', ansible_playbook_python ~ ' -c "import boto3; print(boto3.__version__)"') }}
  delegate_to: localhost
